# - Find protobuf
# Find the native protobuf includes and library
#
#  PROTOBUF_INCLUDE_DIR - where to find google/protobuf/*.h, etc.
#  PROTOBUF_LIBRARIES   - List of libraries when using protobuf.
#  PROTOBUF_FOUND       - True if protobuf found.

IF (PROTOBUF_INCLUDE_DIR)
  # Already in cache, be silent
  SET(PROTOBUF_FIND_QUIETLY TRUE)
ENDIF (PROTOBUF_INCLUDE_DIR)

FIND_PATH(PROTOBUF_INCLUDE_DIR message.h
  /usr/local/include/google/protobuf
  /usr/include/google/protobuf
)

SET(PROTOBUF_NAMES protobuf)
FIND_LIBRARY(PROTOBUF_LIBRARY
  NAMES ${PROTOBUF_NAMES}
  PATHS /usr/lib  /usr/local/lib
)

IF (PROTOBUF_INCLUDE_DIR AND PROTOBUF_LIBRARY)
  SET(PROTOBUF_FOUND TRUE)
  SET( PROTOBUF_LIBRARIES ${PROTOBUF_LIBRARY} )
ELSE (PROTOBUF_INCLUDE_DIR AND PROTOBUF_LIBRARY)
  SET(PROTOBUF_FOUND FALSE)
  SET( PROTOBUF_LIBRARIES )
ENDIF (PROTOBUF_INCLUDE_DIR AND PROTOBUF_LIBRARY)

IF (PROTOBUF_FOUND)
  IF (NOT PROTOBUF_FIND_QUIETLY)
    MESSAGE(STATUS "Found PROTOBUF: ${PROTOBUF_LIBRARY}")
  ENDIF (NOT PROTOBUF_FIND_QUIETLY)
ELSE (PROTOBUF_FOUND)
  IF (PROTOBUF_FIND_REQUIRED)
    MESSAGE(STATUS "Looked for PROTOBUF libraries named ${PROTOBUF_NAMES}.")
    MESSAGE(FATAL_ERROR "Could NOT find PROTOBUF library")
  ENDIF (PROTOBUF_FIND_REQUIRED)
ENDIF (PROTOBUF_FOUND)

MARK_AS_ADVANCED(
  PROTOBUF_LIBRARY
  PROTOBUF_INCLUDE_DIR
  )

