#!/bin/sh
#
# description: Starts and stops the xmlserver daemon


# Source function library.
if [ -f /etc/init.d/functions ] ; then
  . /etc/init.d/functions
elif [ -f /etc/rc.d/init.d/functions ] ; then
  . /etc/rc.d/init.d/functions
else
  exit 1
fi

# Avoid using root's TMPDIR
unset TMPDIR

# Source networking configuration.
. /etc/sysconfig/network


RETVAL=0
start() {
        KIND="xmlServer"
        echo -n $"Starting $KIND services: "
        daemon  ./xmlsrv.sh & 
        RETVAL=$?
	echo 
        [ $RETVAL -eq 0 ] && touch /var/lock/subsys/XmlSrv || \
		RETVAL=1
	return 0
	##return $RETVAL
}

stop() {
        KIND="xmlServer"
        echo -n $"Shutting down $KIND services: "
        killproc XmlSrv
        RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/XmlSrv
        return $RETVAL
}

restart() {
        stop
        start
}
rhstatus() {
        status  XmlSrv
        return $?
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        restart
        ;;
  status)
        rhstatus
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|status}"
        exit 2
esac

exit $?

